### PR TITLE
fixing sphinx warnings

### PR DESCRIPTION
**Pull request by SaraOgaz**
Testing to see if Travis finishes...  runs with no warnings or errors on my mac using "python setup.py build_docs"

### CODE REVIEW

**Comment by SaraOgaz** [comment]
Well, I got two of the errors gone.  I _think_ it was some of the /'s in the notebooks.  It was translating as some kind of newline thing.  Still figuring out that second one..  might end up just canceling this pull request and add the changes into another pull.

**Comment by justincely** [comment]
@SaraOgaz , you want this one pulled in still?

**Comment by SaraOgaz** [comment]
@justincely still trying to fix that last error, will let you know when I"m "done".  Thanks!

**Comment by SaraOgaz** [comment]
Deleting this pull request, don't need it anymore.

**Pull request closed without merging**
